services:
  # MongoDB Service
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - tallerproyectos2_default

  # Backend Service (Development with hot-reload)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: critico-backend-dev
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    depends_on: # <-- AÑADE ESTO
      - mongo   # <-- Y ESTO
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - tallerproyectos2_default

  # Frontend Service (Development with hot-reload)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: critico-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000/api
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - tallerproyectos2_default

networks:
  tallerproyectos2_default:
    external: true